import {test} from 'node:test';
import assert from 'node:assert/strict';
import {initial,buy,runDay,projectDay,trainTeam,capacity,cafePayroll} from '../engine.js';
import {openBusiness,buyBusinessStock,configureBusiness,businessTypes} from '../ventures.js';
import {decodeGame,encodeGame} from '../storage.js';
function advance(day){const s=initial();s.cash=100000;while(s.day<day){if(s.stock<100)buy(s,100,'wholesale');runDay(s,()=>0)}return s;}
test('abertura exige desbloqueio e caixa e não duplica negócios',()=>{const s=initial();assert.equal(openBusiness(s,'bakery'),false);const ready=advance(8),before=ready.cash;assert.equal(openBusiness(ready,'bakery'),true);assert.equal(ready.cash,before-2000);assert.equal(ready.ventures[0].stock,0);assert.equal(openBusiness(ready,'bakery'),false);assert.equal(openBusiness(ready,'market'),false);assert.equal(openBusiness(ready,'toString'),false)});
test('cada negócio mantém estoque, preço e equipe próprios',()=>{const s=advance(15);openBusiness(s,'bakery');openBusiness(s,'market');const cafeStock=s.stock;assert.equal(buyBusinessStock(s,'bakery',30),true);assert.equal(s.ventures[0].stock,30);assert.equal(s.ventures[1].stock,0);assert.equal(s.stock,cafeStock);assert.equal(configureBusiness(s,'bakery','price',15),true);assert.equal(configureBusiness(s,'bakery','price',100),false);assert.equal(configureBusiness(s,'bakery','staff',true),true);assert.equal(s.staff,false);assert.equal(s.ventures[1].staff,false)});
test('resultado consolidado soma lojas e desconta estoque certo sem cobrança duplicada',()=>{const s=advance(15);openBusiness(s,'bakery');openBusiness(s,'market');buyBusinessStock(s,'bakery',100);buyBusinessStock(s,'market',100);const before=structuredClone(s),preview=projectDay(s),r=runDay(s,()=>0);assert.deepEqual(r,preview);assert.equal(r.ventures.length,2);for(const key of ['sold','demand','revenue','expenses','profit','goodsCost'])assert.equal(r[key],r.cafe[key]+r.ventures.reduce((n,v)=>n+v[key],0));assert.equal(s.stock,before.stock-r.cafe.sold);for(let i=0;i<2;i++)assert.equal(s.ventures[i].stock,before.ventures[i].stock-r.ventures[i].sold);assert.equal(s.cash,before.cash+r.revenue-r.expenses);assert.deepEqual(decodeGame(encodeGame(s)),s)});
test('loja sem estoque gera despesa e nenhuma receita',()=>{const s=advance(8);openBusiness(s,'bakery');const r=runDay(s,()=>0).ventures[0];assert.equal(r.sold,0);assert.equal(r.revenue,0);assert.equal(r.profit,-businessTypes.bakery.rent)});
test('treinamento requer funcionário, acrescenta produtividade e salário e tem limite',()=>{const s=initial();assert.equal(trainTeam(s),false);s.staff=true;assert.equal(trainTeam(s),true);assert.equal(s.cash,2200);assert.equal(capacity(s),53);assert.equal(cafePayroll(s),120);assert.equal(trainTeam(s),true);assert.equal(s.cash,1700);assert.equal(capacity(s),61);assert.equal(cafePayroll(s),140);assert.equal(trainTeam(s),false);s.staff=false;assert.equal(capacity(s),25);assert.equal(cafePayroll(s),0)});
test('migra versão publicada com histórico sem perder partida',()=>{const s=advance(10),old=structuredClone(s);for(const key of ['training','ventures','decisions','promotionUntil'])delete old[key];for(const r of old.history){delete r.cafe;delete r.ventures;}const restored=decodeGame(JSON.stringify({version:8,state:old}));assert.deepEqual(restored,s)});
test('capacidade máxima treinada continua salvável em um festival',()=>{const s=advance(20);s.staff=true;s.training=2;s.equipment=true;s.branches=2;s.district='center';s.price=10;s.reputation=100;buy(s,300,'wholesale');const r=runDay(s,()=>.3);assert.equal(r.cafe.sold,101);assert.deepEqual(decodeGame(encodeGame(s)),s)});
